---
first_name:
  validators:
    length:
      label: "&FIRST_NAME"
      min: 1
      max: 20
      message: VALIDATE.LENGTH_RANGE
    required:
      label: "&FIRST_NAME"
      message: VALIDATE.REQUIRED
last_name:
  validators:
    length:
      label: "&LAST_NAME"
      min: 1
      max: 30
      message: VALIDATE.LENGTH_RANGE
locale:
  validators:
    required:
      label: "&LOCALE"
      domain: server
      message: VALIDATE.REQUIRED
subscribed:
  validators:
    member_of: 
      values:
      - '0'
      - '1'
      domain: server
      message: Subscription status must be '1' or '0'.